Rename to iotic

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 if [ "$1" = "purge" ]; then
-    deluser --quiet --system elsewhere > /dev/null || true
-    delgroup --quiet --system elsewhere > /dev/null || true
-    # Cleanup /var/lib/elsewhere
-    rm -rf /var/lib/elsewhere > /dev/null 2>&1 || true
+    deluser --quiet --system iotic > /dev/null || true
+    delgroup --quiet --system iotic > /dev/null || true
+    # Cleanup /var/lib/iotic
+    rm -rf /var/lib/iotic > /dev/null 2>&1 || true
 fi
